version: "3"

services:
  db:
    hostname: typodb
    image: mysql:latest
    container_name: mysql-typo
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  typo3:
    depends_on:
      - db
    restart: always
    build:
      context: ./Dockerfiles/
      dockerfile: Dockerfile
    container_name: typo3
    hostname: typo
    volumes:
      - ./src/typo3conf:/var/www/html/typo3conf
      - ./src/fileadmin:/var/www/html/fileadmin
      - ./src/uploads:/var/www/html/uploads
      - ./src/typo3temp:/var/www/html/typo3temp
    links:
      - db
    ports:
      - "8000:80"

volumes:
     mysql_data:
